---
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filter_chain_match:
        server_names: "*.wikipedia.org"
      filters:
      - name: envoy.tcp_proxy
        config:
          stat_prefix: wikipedia
          access_log:
          - config:
              path: "/dev/stdout"
            name: envoy.file_access_log
          cluster: wikipedia
    - filter_chain_match:
        server_names: "developer.ibm.com"
      filters:
      - name: envoy.tcp_proxy
        config:
          deprecated_v1: true
          value:
            route_config:
              routes:
              - cluster: ibm
            stat_prefix: ibm
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 15001
    filter_chains:
    - filters:
      - name: envoy.tcp_proxy
        config:
          cluster: BlackHoleCluster
          stat_prefix: BlackHoleCluster
    use_original_dst: true
  clusters:
  - name: wikipedia
    connect_timeout: 2.5s
    type: original_dst
    lb_policy: original_dst_lb
  - name: ibm
    connect_timeout: 2.5s
    type: original_dst
    lb_policy: original_dst_lb
  - name: BlackHoleCluster
    connect_timeout: 5.0s
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
